#!/usr/bin/env bash
set -uo pipefail

# ─── Colors & styling ───────────────────────────────────
bold="\033[1m"
dim="\033[2m"
green="\033[0;32m"
red="\033[0;31m"
yellow="\033[0;33m"
cyan="\033[0;36m"
reset="\033[0m"

# ─── IDE catalog ────────────────────────────────────────
# Format: "Label:brew_cask:cli_command:app_bundle"
IDE_CATALOG=(
  "VS Code:visual-studio-code:code:Visual Studio Code.app"
  "Zed:zed:zed:Zed.app"
  "Cursor:cursor:cursor:Cursor.app"
)

# ─── Banner ─────────────────────────────────────────────
echo ""
echo -e "  ${bold}IDE Installer${reset}"
echo -e "  ${dim}─────────────────────────────────${reset}"
echo ""
echo -e "  Available editors:"
echo ""
for i in "${!IDE_CATALOG[@]}"; do
  IFS=: read -r label _ _ app <<< "${IDE_CATALOG[$i]}"
  if [ -d "/Applications/$app" ]; then
    echo -e "    $((i+1))) $label ${dim}(installed)${reset}"
  else
    echo -e "    $((i+1))) $label"
  fi
done
echo ""

# ─── Multi-select ───────────────────────────────────────
printf "  Install (space-separated numbers, or 'none' to skip): "
read -r selection

if [[ "$selection" == "none" || -z "$selection" ]]; then
  echo -e "\n  ${dim}No editors selected.${reset}"
else
  echo ""
  for num in $selection; do
    idx=$((num - 1))
    if [ "$idx" -lt 0 ] || [ "$idx" -ge "${#IDE_CATALOG[@]}" ]; then
      echo -e "  ${yellow}Ignoring invalid option: $num${reset}"
      continue
    fi
    IFS=: read -r label cask _ app <<< "${IDE_CATALOG[$idx]}"
    if [ -d "/Applications/$app" ]; then
      echo -e "  ⏭️  $label ${dim}(already installed)${reset}"
    else
      printf "  Installing %s..." "$label"
      if brew install --cask "$cask" >/dev/null 2>&1; then
        printf "\r  ✅ %s\n" "$label"
      else
        printf "\r  ❌ %s %s\n" "$label" "${red}(run 'brew install --cask $cask' manually)${reset}"
      fi
    fi
  done
fi

# ─── Discover all installed editors ─────────────────────
declare -a INSTALLED_LABELS=()
declare -a INSTALLED_CMDS=()

for entry in "${IDE_CATALOG[@]}"; do
  IFS=: read -r label _ cmd app <<< "$entry"
  if [ -d "/Applications/$app" ]; then
    INSTALLED_LABELS+=("$label")
    INSTALLED_CMDS+=("$cmd")
  fi
done

if [ ${#INSTALLED_LABELS[@]} -eq 0 ]; then
  echo -e "\n  ${yellow}No editors found. Skipping default selection.${reset}\n"
  exit 0
fi

# ─── Default editor selection ───────────────────────────
echo ""
if [ ${#INSTALLED_LABELS[@]} -eq 1 ]; then
  DEFAULT_CMD="${INSTALLED_CMDS[0]}"
  echo -e "  Default editor: ${bold}${INSTALLED_LABELS[0]}${reset} (only editor installed)"
else
  echo -e "  ${bold}Pick your default editor:${reset}"
  echo ""
  for i in "${!INSTALLED_LABELS[@]}"; do
    echo -e "    $((i+1))) ${INSTALLED_LABELS[$i]}"
  done
  echo ""
  printf "  Default [1]: "
  read -r default_choice
  default_choice=${default_choice:-1}
  idx=$((default_choice - 1))
  if [ "$idx" -ge 0 ] && [ "$idx" -lt "${#INSTALLED_LABELS[@]}" ]; then
    DEFAULT_CMD="${INSTALLED_CMDS[$idx]}"
  else
    DEFAULT_CMD="${INSTALLED_CMDS[0]}"
  fi
fi

# ─── Write config ───────────────────────────────────────
cat > "$HOME/.editor_env" << EOF
# Generated by dotfiles/ide.sh
export EDITOR="$DEFAULT_CMD --wait"
export VISUAL="\$EDITOR"
EOF

# Set editor in ~/.gitconfig.local (preserves [user] and other sections)
git config --file "$HOME/.gitconfig.local" core.editor "$DEFAULT_CMD --wait"

echo ""
echo -e "  ${green}Default editor set to: ${bold}$DEFAULT_CMD${reset}"
echo -e "  Written: ${dim}~/.editor_env${reset}, ${dim}~/.gitconfig.local${reset}"
echo -e "  ${dim}Open a new shell to pick up changes.${reset}"
echo ""
