apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: REPLACE_APP_NAME
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: gcr.io/REPLACE_PROJECT_ID/REPLACE_APP_NAME
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
